main/main/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    
]

main/myhome/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('book/<int:book_id>', views.BookDetail.as_view(), name='book_detail'),
    
]

main/myhome/models.py
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()


    def __str__(self):
        return self.name

main/myhome/forms.py
from django import forms 


class BooksearchForms(forms.Form):
    search = forms.CharField()

main/myhome/views.py
from django.shortcuts import render
from django.views import View

from .forms import BooksearchForms
from .Documents import BookDocument
from .models import Book



class Home(View):
    from_class = BooksearchForms

    def get(self,request):
        results = {}
        if request.GET.get('search'):
            results = BookDocument.search().query('match', name=request.GET['search'])

        return render(request,
         'home/home.html',
         {'form':self.form_class,
         'results':request}
         )


class BookDetail(View):
    def get(self,request,book_id):
        book = Book.objects.get(id=book_id)
        return render(request, 'home/book_detail.html', {'book':book})
        

main/myhome/templates/home/book_detail.html
<p>{{ book.name }}</p>
<p>{{ book.author }}</p>
<p>{{ book.descriptions }}</p>

main/myhome/templates/home/home.html
<h3>Home</h3>

<form action="">
{{ form }}
<input type="submit" value="search">

</form>

<p>

    {% for result in results %}
        <p><a href="{% url 'home:book_detail' result.meta.id %}">{{ result.name }}</a></p>
    {% endfor %}
</p>